### ISSUE TITLE
請問如何設定搜尋條件?

### ISSUE THREAD

**Issue by khjht260** [linsamtw/PTTData#4]
您好
若我想select文章名稱中有「周杰倫」這三個字的文章
要如何寫code?
又或是推文數要在20以上的文章才被sekect出來
語法要怎寫??

謝謝您

**Comment by linsamtw** [comment]
要搜尋的話，先把 data 讀到你的電腦上，再用 pandas & re 等套件，去做篩選

例如， 
for ar in article:
     if '周杰倫' in ar: 
           print(True)

基本上用 python 做你要的操作，不難
