### ISSUE TITLE
Gossiping版是不是到 2019/03/25 後就沒跟新了

### ISSUE THREAD

**Issue by ton11111** [linsamtw/PTTData#5]
Gossiping版是不是到 2019/03/25 後就沒跟新了

**Comment by linsamtw** [comment]
已更新

**Comment by donnydonny123** [comment]
請問我們需要做何種改動才能下載到更新後的新資料 ?
我用相同的API還是查不到3/25後的資料

感謝

**Comment by linsamtw** [comment]
修復中

donnydonny123 <notifications@github.com> 於 2019年11月20日 週三 下午4:32寫道：
